title: FLS Wiesbaden status page
languageCode: de
params:
  shortDateFormat: 15:04 — Jan 2
  meta_description: This status page provides updated information about our FLS
    Wiesbaden systems normal operation, incidents that may happen and their
    resolution.
  systems:
    - name: FLS Homepage
      link: https://www.fls-wiesbaden.de/
    - name: Schulportal
      description: Our company public facing website
      link: https://start.schulportal.hessen.de/6328
    - name: Ticketsystem
      description: Our company customer support site
      link: https://support.fls-wiesbaden.de/
    - name: Moodle
      link: https://mo6328.schule.hessen.de/
    - name: BBB-Server
      link: https://app.bbbserver.de/de/login
  dateFormat: January 2, 2006 at 14:45
  disqusShortname: null
  timezoneString: UTC+2
  logo: /images/clearstatus.svg
  description_header: Information about <a class='text-grey-darkest' title='Visit
    fls-wiesbaden.de' href='https://www.fls-wiesbaden.de/'>example</a> systems
    operations.<br />Subscribe to <a class='text-grey-darkest' href='%s'
    >RSS</a><br />to be alerted of new events.
  copyrightHolder: FLS Wiesbaden
  eventsPerPage: 10
  iconType: image/png
  groups: []
  icon: /images/clearstatus.png
  description_footer: <a class='text-grey-darkest' title='Visit fls-wiesbaden.de'
    href='https://fls-wiesbaden.de/'>FLS-Wiesbaden</a> provides open-source
    software for all kind of sectors.
